// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftTouchSearch.Data;

#nullable disable

namespace SoftTouchSearch.Data.Migrations.Import
{
    [DbContext(typeof(ImportDbContext))]
    [Migration("20250406140016_AddMetadata")]
    partial class AddMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("SoftTouchSearch.Data.Models.ChapterImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("SoftTouchSearch.Data.Models.EpisodeImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TapasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlExternal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("SoftTouchSearch.Data.Models.ExclusionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExclusionRules");
                });

            modelBuilder.Entity("SoftTouchSearch.Data.Models.EpisodeImport", b =>
                {
                    b.HasOne("SoftTouchSearch.Data.Models.ChapterImport", "Chapter")
                        .WithMany("Episodes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SoftTouchSearch.Data.Models.MetadataEpisode", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("EpisodeImportId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Comments")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Likes")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Mature")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Views")
                                .HasColumnType("INTEGER");

                            b1.HasKey("EpisodeImportId");

                            b1.ToTable("Episodes");

                            b1.WithOwner()
                                .HasForeignKey("EpisodeImportId");
                        });

                    b.Navigation("Chapter");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("SoftTouchSearch.Data.Models.ChapterImport", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
