// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SoftTouchSearch.Data.Migrations.Import
{
    /// <inheritdoc />
    public partial class AddThumbnailDbSet : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ThumbnailImport_Episodes_EpisodeId",
                table: "ThumbnailImport");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ThumbnailImport",
                table: "ThumbnailImport");

            migrationBuilder.RenameTable(
                name: "ThumbnailImport",
                newName: "Thumbnails");

            migrationBuilder.RenameIndex(
                name: "IX_ThumbnailImport_EpisodeId",
                table: "Thumbnails",
                newName: "IX_Thumbnails_EpisodeId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Thumbnails",
                table: "Thumbnails",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Thumbnails_Episodes_EpisodeId",
                table: "Thumbnails",
                column: "EpisodeId",
                principalTable: "Episodes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Thumbnails_Episodes_EpisodeId",
                table: "Thumbnails");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Thumbnails",
                table: "Thumbnails");

            migrationBuilder.RenameTable(
                name: "Thumbnails",
                newName: "ThumbnailImport");

            migrationBuilder.RenameIndex(
                name: "IX_Thumbnails_EpisodeId",
                table: "ThumbnailImport",
                newName: "IX_ThumbnailImport_EpisodeId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ThumbnailImport",
                table: "ThumbnailImport",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_ThumbnailImport_Episodes_EpisodeId",
                table: "ThumbnailImport",
                column: "EpisodeId",
                principalTable: "Episodes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
