// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SoftTouchSearch.Data.Migrations.Search
{
    /// <inheritdoc />
    public partial class AddThumbnailDbSet : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Episodes_Thumbnail_ThumbnailGuid",
                table: "Episodes");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Thumbnail",
                table: "Thumbnail");

            migrationBuilder.RenameTable(
                name: "Thumbnail",
                newName: "Thumbnails");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Thumbnails",
                table: "Thumbnails",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Episodes_Thumbnails_ThumbnailGuid",
                table: "Episodes",
                column: "ThumbnailGuid",
                principalTable: "Thumbnails",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Episodes_Thumbnails_ThumbnailGuid",
                table: "Episodes");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Thumbnails",
                table: "Thumbnails");

            migrationBuilder.RenameTable(
                name: "Thumbnails",
                newName: "Thumbnail");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Thumbnail",
                table: "Thumbnail",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Episodes_Thumbnail_ThumbnailGuid",
                table: "Episodes",
                column: "ThumbnailGuid",
                principalTable: "Thumbnail",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
