// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SoftTouchSearch.Data.Migrations.Search
{
    /// <inheritdoc />
    public partial class AddChapterThumbnails : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "ThumbnailGuid",
                table: "Chapters",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateIndex(
                name: "IX_Chapters_ThumbnailGuid",
                table: "Chapters",
                column: "ThumbnailGuid");

            migrationBuilder.AddForeignKey(
                name: "FK_Chapters_Thumbnails_ThumbnailGuid",
                table: "Chapters",
                column: "ThumbnailGuid",
                principalTable: "Thumbnails",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Chapters_Thumbnails_ThumbnailGuid",
                table: "Chapters");

            migrationBuilder.DropIndex(
                name: "IX_Chapters_ThumbnailGuid",
                table: "Chapters");

            migrationBuilder.DropColumn(
                name: "ThumbnailGuid",
                table: "Chapters");
        }
    }
}
